### ISSUE TITLE
NotImplementedError: Documentation cannot be generated for:

### ISSUE THREAD

**Issue by dschiller** [CMakePP/CMinx#51]
**Describe the bug**
Doc generattion fails.

**To Reproduce**
1. Create doc string like
#[[[
# Note that ConvertUTF.h does not have an include guard so we cannot use unity
# builds.
#]]
2. Generate
3. See error
Traceback (most recent call last):
  File "main.py", line 27, in <module>
  File "cminx/__init__.py", line 70, in main
  File "cminx/__init__.py", line 120, in document
  File "cminx/__init__.py", line 158, in document_single_file
  File "cminx/documenter.py", line 71, in __init__
  File "antlr4/tree/Tree.py", line 151, in walk
  File "antlr4/tree/Tree.py", line 149, in walk
  File "antlr4/tree/Tree.py", line 163, in enterRule
  File "cminx/parser/CMakeParser.py", line 264, in enterRule
  File "cminx/parser/aggregator.py", line 190, in enterDocumented_command
NotImplementedError: Documentation cannot be generated for:
#[[[
# Note that ConvertUTF.h does not have an include guard so we cannot use unity
# builds.
#]]
add_library(linenoise-ngEXCLUDE_FROM_ALL${NI_LINENOISENG_PACKAGE_PATH}/src/ConvertUTF.cpp${NI_LINENOISENG_PACKAGE_PATH}/src/ConvertUTF.h${NI_LINENOISENG_PACKAGE_PATH}/src/linenoise.cpp${NI_LINENOISENG_PACKAGE_PATH}/src/wcwidth.cpp)
[18143] Failed to execute script main
dirk.schiller@C02DT9UMML7H docs % 

**Expected behavior**
Should generate docs

**Additional context**
none

**Comment by AutonomicPerfectionist** [comment]
We currently only support documenting `function()`, `set()`, and `ct_add_test()`. We can certainly add such functionality, however I am unsure how it should be presented in the generated RST. @ryanmrichard do you have any ideas on which directives we should use for that? Perhaps a variable directive plus an admonition specifying it's a library?

**Comment by ryanmrichard** [comment]
It's really documenting how an existing function is being called. The way
we document functions implies that we're documenting the definition of the
function, not an invocation; so that's probably not the way to go. It's not
a variable, so that doesn't right either.

How do we document ct_add_test? Maybe take that functionality and make it
general for documenting any function call?

**Comment by AutonomicPerfectionist** [comment]
`ct_add_test()` is being documented like a function but with an admonition that it's a test. It would be fairly simple to add processing for all documented commands (just replace the `raise NotImplementedError()` with `process_general_function()` or whatever), I'm just not sure what RST to generate for them, since Sphinx has no analog for documenting general function calls. I suggested the variable directive since `add_library()` behaves kinda like setting a global variable and it was the closest Sphinx directive I could think of.

**Comment by ryanmrichard** [comment]
Gotcha. So maybe the question is for @dschiller then; what do you want it to do?

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist to circle back to this, I vote we do the `ct_add_test` route and generalize it so that the admonition is the something like `invocation of <name of the function>`
